import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import HeaderWrapper from "@/components/HeaderWrapper";
import FooterWrapper from "@/components/FooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className="max-w-full bg-red-900">
      <body
        className={`${geistSans.variable} ${poppins.className} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <HeaderWrapper />
        <div className="w-full h-full bg-white">
          <div className="mx-auto max-w-[1440px] w-full">{children}</div>
        </div>
        <FooterWrapper/>
      </body>
    </html>
  );
}

